### ISSUE TITLE
Intermittent mishandling of flips

### ISSUE THREAD

**Issue by omimanav** [alex-berson/reversi#1]
![image](https://user-images.githubusercontent.com/15974661/226211087-a4460e99-d2f5-4ba7-b311-715199ac0ebb.png)

See image. The white piece in the diagonal line is either supposed to be black or allow a corner placement.

**Comment by alex-berson** [comment]
Thank you for bringing this to my attention. Sometimes, when the application is suddenly closed at the moment when a move is made, the color of the disk image on the board can become incorrect. I will consider how to fix this issue.
